### PR TITLE
Release v0.90.0

### PR DESCRIPTION
**Pull request by Hrfreire**
## Contexto
Essa release adiciona remove o uso da rota de verify na hora da realização de saque e também de antecipação. Além disso, corrige pequenos bugs no extrato.

## Checklist
- [x] [EXP-770] Atualizar fluxo de antecipação para passar senha na rota
- [x] [EXP-769] Atualizar fluxo de saque para passar senha na rota /transfers
- [x] [EXP-760] Correção de pequenos bugs no extrato 

## Como testar fluxos de antecipação/saque?
- [ ] Testar realização de saque com senha correta/errada e verificar se acontece o comportamento esperado
- [ ] Testar realização de antecipação com senha correta/errada e verificar se acontece o comportamento esperado

### Caso 1:
- Impersonar com company 1(Dados da company no card do jira EXP-760) e no extrato pesquisar pelo dia 01/02/2021
- [ ] Verificar se as taxas pagar.me aparece positiva e que a soma (considerar sinal) de todos os card, bate com o total liquido.

### Caso 2:
- Impersonar com company 2 (Dados da company no card do jira EXP-760) e no extrato pesquisar pelo dia 09/02/2021
- [ ] Procurar pela transferência que falhou na tabela de extrato, e verificar se a descrição mostra que a transferência falhou, e que o valor aparece no coluna de entrada e não de saída.

[EXP-770]: https://mundipagg.atlassian.net/browse/EXP-770
[EXP-769]: https://mundipagg.atlassian.net/browse/EXP-769
[EXP-760]: https://mundipagg.atlassian.net/browse/EXP-760

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 549ee2ca4011218c08bd90c7ddb933bd9b8d5f44
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4c05b9a2560811fbd1f498483bee17f97e967721
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: b81d7ae273849514babd936d3323af1375b5767f
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 549ee2ca4011218c08bd90c7ddb933bd9b8d5f44
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4c05b9a2560811fbd1f498483bee17f97e967721
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: b81d7ae273849514babd936d3323af1375b5767f
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 549ee2ca4011218c08bd90c7ddb933bd9b8d5f44
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4c05b9a2560811fbd1f498483bee17f97e967721
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: b81d7ae273849514babd936d3323af1375b5767f
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 549ee2ca4011218c08bd90c7ddb933bd9b8d5f44
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4c05b9a2560811fbd1f498483bee17f97e967721
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: b81d7ae273849514babd936d3323af1375b5767f
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — APPROVED** [review]
### Antecipações / Saque 
- [x] Testar realização de saque com senha correta/errada e verificar se acontece o comportamento esperado
 - [x] Testar realização de antecipação com senha correta/errada e verificar se acontece o comportamento esperado
 
 ### Extrato
(Feito com Hugo)
- [x]  Verificar se as taxas pagar.me aparece positiva e que a soma (considerar sinal) de todos os card, bate com o total liquido. 
- [x] Procurar pela transferência que falhou na tabela de extrato, e verificar se a descrição mostra que a transferência falhou, e que o valor aparece no coluna de entrada e não de saída.

**Comment by Hrfreire** [comment]
### Antecipações / Saque 
- [x] Testar realização de saque com senha correta/errada e verificar se acontece o comportamento esperado
 - [x] Testar realização de antecipação com senha correta/errada e verificar se acontece o comportamento esperado

- Os bugs no extrato testei com o Diego

**Comment by ThaisRobba** [comment]
### Antecipações / Saque 
- [x] Testar realização de saque com senha correta/errada e verificar se acontece o comportamento esperado
- [x] Testar realização de antecipação com senha correta/errada e verificar se acontece o comportamento esperado

**Review by ThaisRobba — APPROVED** [review]

**Pull request merged**
