### PR TITLE
Fix anticipation options

### PR DESCRIPTION
**Pull request by julianasobreira**
## Contexto
Esse PR persiste as alterações feitas nas configurações de company no state do redux, de forma a manter o estado da aplicação consistente.

## Checklist
- [x] Criar a action updateCompany 
- [x] Guardar novas configurações de antecipação no estado local

### CODE REVIEW

**Review by zignd — APPROVED** [review]

**Review by edumoreira1506 — APPROVED** [review]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4cbb819499413b8c855930d03b1db9f89b7dd19
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4cbb819499413b8c855930d03b1db9f89b7dd19
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4cbb819499413b8c855930d03b1db9f89b7dd19
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4cbb819499413b8c855930d03b1db9f89b7dd19
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by zignd — APPROVED** [review]

**Review by edumoreira1506 — APPROVED** [review]

**Pull request merged**
