### PR TITLE
chore: update .editorconfig add rules

### PR DESCRIPTION
**Pull request by andreolvr**
Adicionei duas regras, uma para garantir que todos os arquivos serão UTF-8 e outra para remover os espaços em branco desnecessários no fim das linhas.

### CODE REVIEW

**Comment by derekstavis** [comment]
Whoa, forgot CircleCI is breaking because of [Percy](github.com/percy/percy-storybook). I will push a quick fix and then I will ping you to rebase your branch into master, sounds good?

**Comment by andreolvr** [comment]
Sounds good, but i'm not quite sure about what i'm supposed to do. After you ping me, should i create a new pull request?

**Comment by derekstavis** [comment]
It's merged on #337. You don't need to create another pull-request. It's easier to rebase your branch:

I'm assuming the name of your remote is `origin`.

1. Add our remote to your clone:

```bash
git remote add origin pagarme https://github.com/pagarme/pilot.git
```

2. Fetch the contents of our remote into your clone

```bash
git fetch pagarme
```

3. Rebase our master branch into yours

```bash
git rebase pagarme/master update/editorconfig
```

4. Force push to your branch to update the pull request

```bash
git push origin update/editorconfig -f
```

Yay! :tada: you have updated your branch to be in sync with our master!! This should be sufficient to make this PR green now!!

**Comment by andreolvr** [comment]
Ok, I'll do this whitin today, when i get home! :smiley:

**Comment by derekstavis** [comment]
OK. Until there I will merge #334 too, but the procedure should be the same!

**Comment by andreolvr** [comment]
Done.

**Comment by derekstavis** [comment]
Hey, you got it!! But sorry, I've merged stuff after your rebase! Would you mind rebasing it again? 🤕

**Comment by andreolvr** [comment]
Why do i have to rebase my branch everytime a new pull request is merged? Did the merged pull request modified .editorconfig file? Is it normal?

**Comment by derekstavis** [comment]
Everytime a new pull request is merged your branch gets out of date with master's content. We require branches to be merged to be up to date with master to force contributors to rebase and run their changes with most current master. This is enforced to make people 100% sure that newer changes works great with older changes.

**Comment by andreolvr** [comment]
But it WOULD work if i did not rebase my branch, right? Is it an internal project rule?

**Comment by derekstavis** [comment]
In this specific pull request it would work without issues. And yeah, it's an internal project rule. It's there because even as no code conflict could happen while merging, a possible visual issue could be introduced because of version incompatibility (think a CSS class could be remvoed in a newer revision and the non-conflicting pull request is still using the older class name).

**Comment by andreolvr** [comment]
Ok, i did it 👍.

**Comment by andreolvr** [comment]
Do i need to change something, or is it ok?

**Comment by derekstavis** [comment]
Sorry for the delay!

Clicking the "Update branch" button on Github or doing `git pull origin <branch>` creates a merge commit. Merge commits aren't allowed in pull requests because it confuses the history and makes it difficult to keep a linear history.

To undo the merge commit you can use `git rebase <commit sha>`, then use the rebase method to update the branch based on master.

**Comment by andreolvr** [comment]
Oh, my mistake. I think it's ok now. 😄

**Comment by derekstavis** [comment]
Thanks!! 🎉

**Pull request merged**
