### PR TITLE
PR - Fix de issues encontradas dentro de configurações em detalhes do recebedor

### PR DESCRIPTION
**Pull request by gmbarroso**
## Contexto
Geramos um novo link para teste das mudanças feitas na tela de detalhes do recebedor, porém, encontramos alguns pequenos detalhes são importantes de estarem resolvidos antes de compartilharmos os links aos nossos clientes.

Este PR está relacionado ao card https://github.com/pagarme/caesar/issues/354

## Checklist
- [x] Exibir a conta bancária selecionada na conta do cliente. Hoje exibimos sempre a primeira opção do `select`.
- [x] Adicionar o Truncate à tela de extrato. Conversar com GreenPhoenix.
- [x] Deixar o botão de exportar da tabela de Balance mais visível (colocar o modo como `enable`

## Screenshots
- Exibir conta bancária selecionada
Peek 2019-05-16 17-54

- Truncate na tabela de Balance
image

- Botão melhor visível
image

## Como testar?
- `git clone` desta repo
- `yarn` ou `yarn install` para instalar todas dependências
- `yarn start` para rodar local

### CODE REVIEW

**Comment by tisoap** [comment]
A página de detalhes de recebedor levanta um erro se você tomar as seguintes ações:

- Altera a conta bancária dele e salva
- Troca para outra aba
- Volta para a aba de configurações
- Expande a configuração de conta bancária

May-21-2019 14-39-51

**Comment by gmbarroso** [comment]
@tisoap Diria que o erro é do capeta! :sweat_smile::sweat_smile::sweat_smile:

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cd21f1d750f09fb8fa7d20799210fe41d9ed9b3a
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: b8783f5a82a3ff2030e8aadc73aba1ca19c97c4b
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cd21f1d750f09fb8fa7d20799210fe41d9ed9b3a
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: b8783f5a82a3ff2030e8aadc73aba1ca19c97c4b
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cd21f1d750f09fb8fa7d20799210fe41d9ed9b3a
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: b8783f5a82a3ff2030e8aadc73aba1ca19c97c4b
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cd21f1d750f09fb8fa7d20799210fe41d9ed9b3a
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: b8783f5a82a3ff2030e8aadc73aba1ca19c97c4b
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21476863342bfbdebf446b64054395249e8f7df3
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 17f425f9c9d2f1cea6f3a56e13f48aa4db74b3cf
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 17f425f9c9d2f1cea6f3a56e13f48aa4db74b3cf
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 17f425f9c9d2f1cea6f3a56e13f48aa4db74b3cf
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 17f425f9c9d2f1cea6f3a56e13f48aa4db74b3cf
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by gmbarroso** [comment]
Estou ciente dos erros no CircleCi e do GitCop. Vou acertar esses erros na segunda. são erros de testes por conta da mudança feita no formatter de `bankAccount`

**Comment by gmbarroso** [comment]
Identifiquei um problema que ocorria ao adicionar um recebedor que adicionava informações adicionais. O problema ocorria quando era inserida uma informação de protocolo sem `http` ou `https`. A validação que atual permite passar uma informação sem esses prefixos. Para corrigir adicionei um commit que atualiza a validação de protocolo.

**Pull request merged**
