### PR TITLE
Release v0.86.0

### PR DESCRIPTION
**Pull request by rsmelo**
## Contexto
Esta release adicionna:
- EXP-639 criação de chave do pix como auto-serviço #1845
- EXP-680 payable: add status confirmed and prepaid #1846

### chaves do pix
- [ ] em uma compay com pix habilitado, no ambiente de testes, acessar a tela de configurações/pix, verificar se é exibida a mensagem informando que não é possível gerar chaves nesse ambiente
- [ ] em uma company com pix habilitado, que já possui chave de pix gerada, acessar o ambiente de live a tela de configurações/pix e verficiar se é exibido a mensagem informado da chave existente
- [ ] em uma company com pix habilitado, que não possui chave de pix gerada, acessar a tela de configurações/pix e verificar se é exibido o botão para criação de chave pix e se a criação funciona
- [ ] em company sem pix habilitado, acessar a tela de configurações a aba de pix não deve ser exibida

### status de payables
- [ ]  acessar o detalhe de transações de alguma transação que possua split e tenha payables com o status confirmed ou prepraid, verificar se a tela carrega normalmente

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d99b4c3e172f78e564688bd8b8a605543b67e6a7
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 49823a7934f060f37af57ad6a074b3c1f812de8d
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: dcbd7596e5b8471633b128aaa6f0fe5bacb900b1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d99b4c3e172f78e564688bd8b8a605543b67e6a7
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 49823a7934f060f37af57ad6a074b3c1f812de8d
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: dcbd7596e5b8471633b128aaa6f0fe5bacb900b1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d99b4c3e172f78e564688bd8b8a605543b67e6a7
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 49823a7934f060f37af57ad6a074b3c1f812de8d
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: dcbd7596e5b8471633b128aaa6f0fe5bacb900b1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d99b4c3e172f78e564688bd8b8a605543b67e6a7
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 49823a7934f060f37af57ad6a074b3c1f812de8d
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: dcbd7596e5b8471633b128aaa6f0fe5bacb900b1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by rsmelo** [comment]
- [x] em uma company com pix habilitado, no ambiente de testes, acessar a tela de configurações/pix, verificar se é exibida a mensagem informando que não é possível gerar chaves nesse ambiente
- [ ] em uma compay com pix habilitado, que já possui chave de pix gerada, acessar o ambiente de live a tela de configurações/pix e verficiar se é exibido a mensagem informado da chave existente
- [x] em uma compay com pix habilitado, que não possui chave de pix gerada, acessar a tela de configurações/pix e verificar se é exibido o botão para criação de chave pix e se a criação funciona

**Comment by Hrfreire** [comment]
- [x] em uma company com pix habilitado, no ambiente de testes, acessar a tela de configurações/pix, verificar se é exibida a mensagem informando que não é possível gerar chaves nesse ambiente
- [ ] em uma company com pix habilitado, que já possui chave de pix gerada, acessar o ambiente de live a tela de configurações/pix e verficiar se é exibido a mensagem informado da chave existente
- [x] em uma company com pix habilitado, que não possui chave de pix gerada, acessar a tela de configurações/pix e verificar se é exibido o botão para criação de chave pix e se a criação funciona
- [x] em company sem pix habilitado, acessar a tela de configurações a aba de pix não deve ser exibida

**Review by Hrfreire — APPROVED** [review]

**Review by diegodsgarcia — APPROVED** [review]
- [x] em uma company com pix habilitado, no ambiente de testes, acessar a tela de configurações/pix, verificar se é exibida a mensagem informando que não é possível gerar chaves nesse ambiente
- [x] em uma company com pix habilitado, que já possui chave de pix gerada, acessar o ambiente de live a tela de configurações/pix e verficiar se é exibido a mensagem informado da chave existente
- [ ] em uma company com pix habilitado, que não possui chave de pix gerada, acessar a tela de configurações/pix e verificar se é exibido o botão para criação de chave pix e se a criação funciona
- [x] em company sem pix habilitado, acessar a tela de configurações a aba de pix não deve ser exibida

**Pull request merged**
