### PR TITLE
Fix max value anticipation D0

### PR DESCRIPTION
**Pull request by marquinhoalm**
## Contexto
O nossa regra atual é que o cliente consegue criar antecipação D0 até as 11h. Acontece que a configuração está incorreta e atualmente está limitando BulkAnticipations em D0 à partir das 10h20m.

Com isso o fix consiste em alterar esse valor para que corresponda a lógica da API.

## Como testar?
Loga na dashboard com o horário do computador alterado para que seja possível testar o limite de horário e ao entrar na tela de antecipação verificar a data oferecida para o cliente.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aabbc09b144ba493137ce7bf76e8380679a04907
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aabbc09b144ba493137ce7bf76e8380679a04907
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aabbc09b144ba493137ce7bf76e8380679a04907
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aabbc09b144ba493137ce7bf76e8380679a04907
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by rsmelo — APPROVED** [review]

**Review by matheusvellone — APPROVED** [review]

**Review by lucianopf — APPROVED** [review]

**Pull request merged**
