### PR TITLE
Onboarding anticipation

### PR DESCRIPTION
**Pull request by zignd**
## Contexto
Nova primeira questão durante o onboarding que irá permitir que o usuário selecione ou não um modelo de antecipação compulsória que esteja mais alinhado ao seu negócio.

## Checklist
- [x] Ainda é necessário fazer o release da nova versão do pagarme-js e consequentemente o bump da versão utilizada aqui.

## Screenshots
image

## Como testar?
Alterar o Root.js para forçar o onboarding a aparecer sempre logo após o login e verifique a funcionalidade.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0310e6cb6fb183c593155f17b09f2b532bf6944a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0310e6cb6fb183c593155f17b09f2b532bf6944a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0310e6cb6fb183c593155f17b09f2b532bf6944a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0310e6cb6fb183c593155f17b09f2b532bf6944a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by julianasobreira — APPROVED** [review]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41a3df586b6c3efd0586e80daf3ffa86fb5aba71
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41a3df586b6c3efd0586e80daf3ffa86fb5aba71
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41a3df586b6c3efd0586e80daf3ffa86fb5aba71
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41a3df586b6c3efd0586e80daf3ffa86fb5aba71
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by edumoreira1506 — APPROVED** [review]

**Review by julianasobreira — APPROVED** [review]

**Pull request merged**
