### PR TITLE
EXP-574 - [Detalhes da transação] Valor líquido aparece errado

### PR DESCRIPTION
**Pull request by oAllanWeb**
## Contexto
Valor liquido não calculava a taxa de antecipação então quando o cliente(antecipação compulsória ) recebia de fato o valor ele era menor do que apresentava na dashboard

## Screenshots

- Problema
bf43405f-7989-4a3a-a7fd-f40725a2a21d

- Resolução

Captura de tela de 2021-03-19 15-31-55

### CODE REVIEW

**Review by diegodsgarcia — COMMENTED** [review]
Ta show demais!!! Deu só um probleminha no circle ci esquisito, eu já vi esse erro porém esqueci como se resolve. Talvez o @allangrds ou o @vagnervst saibam como resolver. 
Também não se esqueça de dar `git pull origin master --rebase`, pois subimos ontem o deploy e está dando conflito com essa branch.

De resto ta show!!  :clap: :clap: :rocket:

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90f3766eb02599bf0d3ec739d209679cf6dc9669
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90f3766eb02599bf0d3ec739d209679cf6dc9669
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90f3766eb02599bf0d3ec739d209679cf6dc9669
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90f3766eb02599bf0d3ec739d209679cf6dc9669
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — APPROVED** [review]

**Review by Hrfreire — APPROVED** [review]

**Pull request merged**
