### PR TITLE
Release - Impersonate 

### PR DESCRIPTION
**Pull request by diegodsgarcia**
Esse release é responsável por adiciona modo Impersonate da Pilot e Também por corrigir bug de antecipações pendentes com datas erradas no extrato.

## PR's
- EXP-723: Criar fluxos de ci/cd para modo impersonar #1864 
- EXP-728 Correções relacionadas ao logout #1857
- EXP-724 Criar tratamento para campo metadata de transaction no modo impersonar #1855 
- EXP-721 atualiza restauração de sessão com chave de impersonação #1854
- EXP-765 Corrigir data de Antecipação pendente

## Como testar?
https://impersonate.stg.pagarme.net/latest/index.html#/account/impersonate
https://impersonate.prd.pagarme.net/

- Logar company com antecipação pendente e verificar se a data mostrada é a data de pagamento e não a data de criação do bulk antecipation

### Observações
- Você deve estar na VPN e possuír o acesso a `api-admin` para efeturar o login e realizar o impersonar em uma company

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ad32525f2a8b66aee58af69c1aba820211f7297c
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by Hrfreire — DISMISSED** [review]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4b553e9cdfcfc32145159cec583e9bf94b2cabe3
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca072517b74093ea45feb39a96e1f88efd6945b5
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 4b553e9cdfcfc32145159cec583e9bf94b2cabe3
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by Hrfreire — APPROVED** [review]
- [x] Teste geral do modo impersonar em PRD, incluindo:
   - Logout
   - Restauração de sessão no refresh da pag
   - metadata nos detalhes de transação
- [x] Testado data de Bulk Antecipation pendente do extrato (Mostar `payment_date` no lugar do `created_at`)

**Review by rsmelo — APPROVED** [review]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9964a191e4fab282f4249b66ecaceb992ac35421
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  


 * Commit: 92c1db981ee17e2621c3402967aaaab51d964d53
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e4ca49fdd178602662560f96c29f4d8d6d76251c
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by Hrfreire — APPROVED** [review]

**Review by rsmelo — APPROVED** [review]

**Pull request merged**
