### PR TITLE
transaction-details: fix bug transação recusada com split_rule

### LINKED ISSUE #1077: Criar fallback de erro para detalhes de transação
### Contexto

Hoje quando há algum status novo vindo para a tela de detalhes de transação acabamos recebendo uma série de erros que normamente estão atrelados aos modelos que utilizamos, um bom exemplo de erro é o da issue #1067. 
A proposta é criarmos um fallback default para este tipo de erro que possa realmente ser útil e não quebrar a interface de detalhes de transação.
### Exemplo

image

### Requisitos e Critérios de Aceite

- [ ] Criar um meio de evitar quebras de interface graves na tela de detalhes de transação.

### PR DESCRIPTION
**Pull request by alalbux**
## Contexto
Esse PR ajusta uma quebra de interface no pilot na tela de detalhe de transação

## Issues linkadas
- [ ] Resolves #1077

## Como testar?
- baixar a branch `fix/transaction-details-fallback-error`
- inicar a pilot (`yarn start`)
- acessar a pagina de detalhes de transação com alguma transação com status recusada e split_rules. 

`para criar uma transação recusada basta passar 6 no no primeiro digito do cvv`

### CODE REVIEW

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 75077241ef34f28cf6ecbffa417cd6e4e82b8a58
  * Good titles doesn't exceed 50 characters. To add more details use the body!
  * Always use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 75077241ef34f28cf6ecbffa417cd6e4e82b8a58
  * Good titles doesn't exceed 50 characters. To add more details use the body!
  * Always use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 2d015df3b551c706f075cb40b6b1f02aa8c50836
  * Always use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by Deivis** [comment]
Sugiro uma abordagem mais clara sobre a validação, neste caso o problema não é a transação ser recusada, mas sim o status das parcelas não existirem para o recebedor. Fiz um commit com uma sugestão de ajuste que ao meu ver é mais apropriada.

**Pull request merged**
