### PR TITLE
feat(Sidebar): persist hide SidebarSummary option in localStorage

### PR DESCRIPTION
**Pull request by Hrfreire**
## Contexto
Esse PR adiciona uma flag no localStorage para armazenar a opção de Esconder/Mostrar o saldo da conta no menu lateral. Anteriormente, caso o usuário optasse por não mostrar o saldo, ao atualizar a página, ou ao fazer o login em outro momento, o saldo aparecia aberto novamente.

## Checklist
- [x] Adiciona flag no localStorage, para salvar salvar status de esconder/mostrar saldo.

## Issues linkadas
- [x] [CRED-313 - Remover componente de saldo do menu lateral](https://mundipagg.atlassian.net/browse/CRED-313)

## Screenshots
image
image

## Como testar?
- Fazer login na dash, escolher para esconder saldo. Dar refresh na página e ver se o saldo continua escondido.
- Fazer login na dash, escolher para esconder saldo. Fazer logout e depois login novamente e ver se o saldo continua escondido.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c7e28d3c1fc85129c09b9731b4fc8a541d93ec
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c7e28d3c1fc85129c09b9731b4fc8a541d93ec
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c7e28d3c1fc85129c09b9731b4fc8a541d93ec
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c7e28d3c1fc85129c09b9731b4fc8a541d93ec
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by allangrds — APPROVED** [review]

**Review by diegodsgarcia — APPROVED** [review]

**Pull request merged**
