### PR TITLE
Bug fix: download do comprovante de estorno

### PR DESCRIPTION
**Pull request by edumoreira1506**
## Contexto

Em alguns casos de transações estornadas, ao fazer o download do comprovante de estorno, um erro era estourado no console:

Screenshot from 2020-12-23 10-26-51

E com esse erro estourando o usuário não conseguia fazer o download do comprovante de estorno. Baiscamente, esse erro era causado pelo tipo de formato do retorno da função `getRefundsBankAccounts`.

No momento que o usuário clica para exportar o comprovante de estorno, uma primeira request é disparada para `/refunds`, que retorna uma estrutura mais ou menos assim:
```json
[{
      "amount": 123456,
      "bank_account_id": null,
      "charge_fee_recipient_id": null,
      "date_created": "2020-12-16T17:46:52.678Z",
      "date_updated": "2020-12-16T17:46:52.678Z",
      "fee": 123,
      "fraud_coverage_fee": 0,
      "id": "FAKE_ID",
      "local_transaction_id": null,
      "metadata": {},
      "object": "refund",
      "status": "refunded",
      "transaction_id": 12345678,
      "type": "credit_card"
}]
```

Depois dessa request disparada, esse "array de refunds" é transformado em um array de `bankAccountIds` dentro da função `getRefundsBankAccounts`, exemplo de array de `bankAccountIds`: `[123, 456]`, e o erro estava justamente nessa parte, porque o front estava pegando o array e enviando ele como parametro para o SHOW de bank accounts, resultando numa request que bate num endpoint tipo esse: `/bank_accounts/123,456`, e isso causava o erro:

image

Além de que, mesmo que fosse enviado apenas um id nesse método show, ele iria retornar um objeto, ao invés de um array, causando aquele erro mostrado acima. Foram escritos testes que cobrem todos esses casos citados.

## Como testar?
`cd packages/pilot && yarn test src/pages/Transactions/Details/refundReceiptExport/index.test.js`

Você pode alterar o retorno da função `getRefundsBankAccounts` para o modelo antigo e rodar os testes, vai notar que alguns testes ao invés de retornar um array, vai retornar um objeto, que era o que causava o erro.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51d4125e4a7aab8e7d1bcd1f18b8c6f3b97bcf1e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51d4125e4a7aab8e7d1bcd1f18b8c6f3b97bcf1e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51d4125e4a7aab8e7d1bcd1f18b8c6f3b97bcf1e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51d4125e4a7aab8e7d1bcd1f18b8c6f3b97bcf1e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 308101e1a702276408b487a91a41dd068af4433e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 308101e1a702276408b487a91a41dd068af4433e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 308101e1a702276408b487a91a41dd068af4433e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 308101e1a702276408b487a91a41dd068af4433e
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9083a041065f51fc966ca9c82643785b47708f0
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9083a041065f51fc966ca9c82643785b47708f0
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9083a041065f51fc966ca9c82643785b47708f0
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9083a041065f51fc966ca9c82643785b47708f0
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by julianasobreira — APPROVED** [review]

**Review by zignd — APPROVED** [review]

**Pull request merged**
