### PR TITLE
[EXP-790] Corrige conversões dos valores do localstorage para null, quando executado logout

### PR DESCRIPTION
**Pull request by diegodsgarcia**
## Contexto
No modo Impersonate, quando é executado o logout, o estado inicial no reducer a qual se baseia o localstorage para ser salvo, não cria o objeto `impersonateKey`, como estado inicial. Com isso no localstorage o valor da chave se manterá `undefined` e com isso irá quebrar a aplicação quando é convertido automaticamente pela lib `redux-localstorage-simple` em JSON (utilizando o `JSON.parse()`)

## Checklist
- [x] Adiciona `impersonateKey` no estado inicial 

## Issues linkadas
- [x] [EXP-790: Corrige conversões dos valores do localstorage para null, quando executado logout](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&modal=detail&selectedIssue=EXP-790)

## GIF do erro
finalmente

## Como testar?
- Execute a modo pilot no modo Impersonate
- Faça logout e verifique se a váriavel `impersonateKey` no localstorage foi mantida `null`

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f30fafd138880744ae3aad2e13f9b0ed0954cadc
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f30fafd138880744ae3aad2e13f9b0ed0954cadc
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f30fafd138880744ae3aad2e13f9b0ed0954cadc
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f30fafd138880744ae3aad2e13f9b0ed0954cadc
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by Hrfreire — APPROVED** [review]

**Review by LucasRichter — APPROVED** [review]

**Pull request merged**
