### PR TITLE
Refactor README to add project brief

### LINKED ISSUE #197: Propósito do produto
Cade o propósito / visão do produto? Deveria estar na primeira linha na minha visão.

### PR DESCRIPTION
**Pull request by derekstavis**
This refactors the README file to include the project brief.

As the text became longer to read, the first three quarters of project timeline were inverted and compressed inside a `<details>` tag.

Resolves #197

### CODE REVIEW

**Comment by felquis** [comment]
Does it attempt to close #197?

**Comment by derekstavis** [comment]
Yes. Just added it to OP.

**Comment by mccraveiro** [comment]
@derekstavis It's missing the gitter link :)

**Comment by felquis** [comment]
```txt
[![Join the chat at https://gitter.im/pagarme/react-event-components](https://badges.gitter.im/pagarme/pilot.svg)](https://gitter.im/pagarme/pilot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```


[Join the chat at https://gitter.im/pagarme/react-event-components](https://gitter.im/pagarme/pilot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Pull request merged**
