### PR TITLE
buttons: fix proptypes

### PR DESCRIPTION
**Pull request by bukinoshita**
Button has only 3 possible type values. Proptypes should accept one of those 3 instead of just a `string`

### CODE REVIEW

**Comment by LeoNero** [comment]
@bukinoshita thanks for your PR :D  

@derekstavis There's a error with travis: `Error: The PERCY_TOKEN environment variable is missing.` Do you have any ideas why this is happening?

**Comment by derekstavis** [comment]
@LeoNero @bukinoshita I have fixed the CI issue in #271. Would you mind rebasing the pull request on current master? Thanks!

**Comment by bukinoshita** [comment]
ops, pressed `update branch` and it merged instead. I can re-open in another PR if you'd like

**Comment by derekstavis** [comment]
If you don't mind, just `git rebase -i` and squash into one commit, then `git push -f` into your branch to update this pull request.

**Comment by derekstavis** [comment]
Thanks a lot!!

**Comment by felquis** [comment]
:D

**Pull request merged**
