### PR TITLE
anticipation-options: add labels to describe sections

### PR DESCRIPTION
**Pull request by zignd**
## Contexto
Adiciona duas labels para indicar o propósito de cada secção na área de prazos de recebimento.

## Screenshots
image

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9ae3ac0ce4576c87a40381f371205fcd961f833d
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9ae3ac0ce4576c87a40381f371205fcd961f833d
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9ae3ac0ce4576c87a40381f371205fcd961f833d
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9ae3ac0ce4576c87a40381f371205fcd961f833d
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by edumoreira1506 — APPROVED** [review]

**Review by julianasobreira — APPROVED** [review]

**Pull request merged**
