### PR TITLE
Previne criação de BA D+0 no dia 24/12

### PR DESCRIPTION
**Pull request by murilohns**
## Contexto
Previne a criação de antecipações D+0 dia 24/12.

## Issues linkadas
https://pagarme.slack.com/archives/C04M9RJFL/p1608569087054800

## Screenshots

Nesse teste alterei a data da minha máquina pra 24/12 08:10

pilot

## Como testar?

Altere a data do seu computador para 24/12 antes de 11h e tente criar uma antecipação para esse dia.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4ff6097a6ef799edbb7f7a7aa827f5444039718
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4ff6097a6ef799edbb7f7a7aa827f5444039718
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4ff6097a6ef799edbb7f7a7aa827f5444039718
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4ff6097a6ef799edbb7f7a7aa827f5444039718
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by czaghi — APPROVED** [review]

**Review by vagnervst — APPROVED** [review]
Ficou show! Só ajustar a mensagem do commit pro padrão de `<scope>: <action> message`, talvez algo como: "anticipation: add christmas eve d0 validation"

**Review by rsmelo — APPROVED** [review]

**Pull request merged**
