### PR TITLE
EXP-724 Criar tratamento para campo metadata de transaction no modo impersonar

### PR DESCRIPTION
**Pull request by Hrfreire**
## Contexto
Este PR adiciona tratamento para mapear o campo de metadata no modo impersonar. Neste modo o metadata é retornado no formato `metadata_{companyId}`, dentro da rota de transaction.

Como na parte de transactions no cockpit, não se tem o company_id, foi feito um tratamento para localizar uma key que comece com `metadata_` e atribuir esse valor a key de `metadata` que é retornada pelo transactionSpec.

Além disso, foi corrigido timezone de um teste do cockpit que estava falhando.

## Checklist
- [x] Criar função para procure por uma key `metadata_{companyId}` e também por `metadata`
- [x] Usar essa função nos locais onde se acessa o metada 
- [x] Corrigir timezone de teste de search de transactions

## Screenshots
Antes: Card de metadata não aparece na tela de detalhes de uma transação quando impersornado.

Depois:
image

## Como testar?
1. Buildar o cockpit
2. Rodar a pilot usando o comando `yarn run impersonate`
3. Achar no metabase uma company em live, que tenha uma transação que possua metadata.
4. Fazer o login na tela de impersonar, passando o id dessa company
5. Acessar a tela de detalhes da transação com metadata
6. Verificar se o card de metada é exibido

OBS 1: É necessário ser uma company em live, pois o impersonate roda com a url de produção
OBS 2: É necessário estar na VPN.
OBS 3: É necessário ter acesso de leitura da dash admin.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1bda15ac0564254c389af878559b8598a811dac1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1bda15ac0564254c389af878559b8598a811dac1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1bda15ac0564254c389af878559b8598a811dac1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1bda15ac0564254c389af878559b8598a811dac1
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by rsmelo** [comment]
@Hrfreire impersonando uma company especifiica que tem transação reprocessada ainda tem referencia a `.metadata ` nesse arquivo, pensar em como fazer o tratamento

https://github.com/pagarme/pilot/blob/fix/impersonate-metadata/packages/cockpit/dist/transactions/details/isReprocessable.js

vou passar o company id e transaction no slack pq o repo é aberto

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d5e1b59ec968c20b30b0faf026331cf8b16efa37
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d5e1b59ec968c20b30b0faf026331cf8b16efa37
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d5e1b59ec968c20b30b0faf026331cf8b16efa37
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d5e1b59ec968c20b30b0faf026331cf8b16efa37
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d77208345994fee59a6f96d3d22b1a0dfd52ae03
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d77208345994fee59a6f96d3d22b1a0dfd52ae03
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d77208345994fee59a6f96d3d22b1a0dfd52ae03
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d77208345994fee59a6f96d3d22b1a0dfd52ae03
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by rsmelo — APPROVED** [review]

**Pull request merged**
