### PR TITLE
release v0.87.4

### PR DESCRIPTION
**Pull request by rsmelo**
## contexto

essa release corrige o relatório de exportação de listagem de transações, corrigindo os valores da coluna recipient_id para transações com split_rule

## pr contidos na release
- EXP-730 - Transações - Coluna de Recebedores está filtrando o ID errado #1858

## como testar
- acessar o link da release
- acessar a tela de listagem de transações
- garantir que possui transações com split_rule
- exportar a tabela
- conferir a coluna de recebedores se o id informado é realmente de recebedores e não de split_rules

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fdc62ac06a503f748ea8fa5588f05212a299f1f3
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fdc62ac06a503f748ea8fa5588f05212a299f1f3
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fdc62ac06a503f748ea8fa5588f05212a299f1f3
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fdc62ac06a503f748ea8fa5588f05212a299f1f3
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by Hrfreire — APPROVED** [review]

**Review by diegodsgarcia — APPROVED** [review]

**Pull request merged**
